//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudentsHelpTerminal
{
    using System;
    using System.Collections.Generic;
    
    public partial class STAFF_REF
    {
        public int ID_STAFF_REF { get; set; }
        public int STAFF_ID { get; set; }
        public System.DateTime DATE_ACTION { get; set; }
        public int SUBDIV_ID { get; set; }
        public int APPOINT_ID { get; set; }
        public int GROUP_WT_ID { get; set; }
        public Nullable<int> DOCUMENTS_ID { get; set; }
        public System.DateTime LAST_TIMESTAMP { get; set; }
    }
}
