//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudentsHelpTerminal.Models.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class STAFF
    {
        public int ID_STAFF { get; set; }
        public string LAST_NAME { get; set; }
        public string FIRST_NAME { get; set; }
        public string MIDDLE_NAME { get; set; }
        public string TABEL_ID { get; set; }
        public byte[] PORTRET { get; set; }
        public System.DateTime DATE_BEGIN { get; set; }
        public Nullable<System.DateTime> DATE_DISMISS { get; set; }
        public int VALID { get; set; }
        public int TEMPORARY_ACC { get; set; }
        public string ID_FROM_1C { get; set; }
        public int DELETED { get; set; }
        public int STAFF_STATE { get; set; }
        public System.DateTime LAST_TIMESTAMP { get; set; }
        public int DIN_PAY_SCHEMES_ID { get; set; }
        public int DIN_GRAPHS_ID { get; set; }
        public decimal DIN_GRANT_MEASURE_SPENDED { get; set; }
        public decimal DIN_COST_VALUE_SPENDED { get; set; }
        public string PATH_ACTDIR { get; set; }
        public string PATH_ACTDIR_LOGIN { get; set; }
        public string PATH_ACTDIR_DOMAIN { get; set; }
        public string SHORT_FIO { get; set; }
        public string FULL_FIO { get; set; }
    }
}
