//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudentsHelpTerminal.Models.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class STAFF_FACE_PORTRETS
    {
        public int ID_STAFF_FACE_PORTRETS { get; set; }
        public Nullable<int> STAFF_ID { get; set; }
        public string TRASSIR_FACE_ID { get; set; }
        public byte[] PORTRET { get; set; }
        public Nullable<int> USE_IN_RECOGNITION { get; set; }
        public int DELETED { get; set; }
    }
}
