//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudentsHelpTerminal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class STOP_CARDS_DESCRIPTION
    {
        public int ID_STOP_CARDS { get; set; }
        public int CARD_ID { get; set; }
        public string DESCRIPTION { get; set; }
        public int POSSIBLE_RECALL { get; set; }
    }
}
