//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudentsHelpTerminal.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class StudentsDBContext : DbContext
    {
        public StudentsDBContext()
            : base("name=StudentsDBContext")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<STAFF> STAFFs { get; set; }
        public virtual DbSet<STAFF_CARDS> STAFF_CARDS { get; set; }
        public virtual DbSet<STAFF_REF> STAFF_REF { get; set; }
        public virtual DbSet<SUBDIV_REF> SUBDIV_REF { get; set; }
    }
}
