//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudentsHelpTerminal.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.8.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public int CardReaderPortBaudRate {
            get {
                return ((int)(this["CardReaderPortBaudRate"]));
            }
            set {
                this["CardReaderPortBaudRate"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public string CardReaderPortName {
            get {
                return ((string)(this["CardReaderPortName"]));
            }
            set {
                this["CardReaderPortName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("E:\\Terminal data")]
        public string PathToMainFolder {
            get {
                return ((string)(this["PathToMainFolder"]));
            }
            set {
                this["PathToMainFolder"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("E:\\Terminal data\\Common")]
        public string CommonDocsDirectoryName {
            get {
                return ((string)(this["CommonDocsDirectoryName"]));
            }
            set {
                this["CommonDocsDirectoryName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(".\\Users.log")]
        public string PathToLogFile {
            get {
                return ((string)(this["PathToLogFile"]));
            }
            set {
                this["PathToLogFile"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public int MaxLogSizeMB {
            get {
                return ((int)(this["MaxLogSizeMB"]));
            }
            set {
                this["MaxLogSizeMB"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(".\\Maps")]
        public string PathToCollegeMapsFolder {
            get {
                return ((string)(this["PathToCollegeMapsFolder"]));
            }
            set {
                this["PathToCollegeMapsFolder"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(".\\Administrators.xml")]
        public string PathToAdminsFile {
            get {
                return ((string)(this["PathToAdminsFile"]));
            }
            set {
                this["PathToAdminsFile"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(".\\Questions.xml")]
        public string PathToQAFile {
            get {
                return ((string)(this["PathToQAFile"]));
            }
            set {
                this["PathToQAFile"] = value;
            }
        }
    }
}
